# Generated by Django 4.2.6 on 2023-10-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peticiones',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('peticion', models.CharField(db_column='Peticion', max_length=255)),
            ],
            options={
                'db_table': 'peticiones',
                'managed': False,
            },
        ),
    ]
